### ISSUE TITLE
CSV에 들어가야할 정보들은 무엇이 있을까요?

### ISSUE THREAD

**Issue by ayanemoona** [OSS-3-MINTAEK/Recommendataion_Place#28]
제주도 지역 이름
장소 이름
장소 유형(먹거리, 카페, 관광지, 산책로)
가격대
별점
리뷰 링크
더 추가하면 좋을 게 있으면 댓글로 남겨주세요

**Comment by devsher** [comment]
특정 기간의 방문자 수,
 평균 체류 시간 등의 정보도 추가할 수 있습니다.
 근데 그 정보가 복잡해지지 않을까요? 모르겠어요.
